display_name: FastCat

icon: ./assets/images/icon.png

keywords:
  - 快猫
  - FastCat
  - Clash
  - ClashMeta
  - Proxy

generic_name: FastCat

categories:
  - Network

startup_notify: true
startup_wm_class: com.fastcat.app

include: []
