display_name: 快猫

icon: ./assets/images/icon.png

keywords:
  - 快猫
  - fastcat
  - Clash
  - ClashMeta
  - Proxy

generic_name: fastcat

categories:
  - Network

startup_notify: true

include: []
