display_name: 快猫
package_name: fastcat
maintainer:
  name: chen08209
  email: chen08209@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev
  - fonts-noto-cjk

keywords:
  - 快猫
  - FastCat
  - Clash
  - ClashMeta
  - Proxy

generic_name: FastCat

categories:
  - Network

startup_notify: true
startup_wm_class: com.fastcat.app

postinstall_scripts:
  - for name in 'fastcat' 'FastCat' '快猫' 'fl_clash' 'fastcatCore'; do if command -v pkill >/dev/null 2>&1; then pkill -TERM -x "$name" >/dev/null 2>&1 || true; elif command -v killall >/dev/null 2>&1; then killall -TERM "$name" >/dev/null 2>&1 || true; fi; done
  - sleep 1
  - for name in 'fastcat' 'FastCat' '快猫' 'fl_clash' 'fastcatCore'; do if command -v pkill >/dev/null 2>&1; then pkill -KILL -x "$name" >/dev/null 2>&1 || true; elif command -v killall >/dev/null 2>&1; then killall -KILL "$name" >/dev/null 2>&1 || true; fi; done
  - if [ -f /usr/share/applications/FastCat.desktop ]; then cp /usr/share/applications/FastCat.desktop /usr/share/applications/com.fastcat.app.desktop; fi
  - rm -f /usr/share/applications/FastCat.desktop /usr/share/applications/fastcat.desktop
postuninstall_scripts:
  - rm -f /usr/share/applications/com.fastcat.app.desktop /usr/share/applications/FastCat.desktop /usr/share/applications/fastcat.desktop
