display_name: 快猫
package_name: fastcat
maintainer:
  name: chen08209
  email: chen08209@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - 快猫
  - FastCat
  - Clash
  - ClashMeta
  - Proxy

generic_name: FastCat

categories:
  - Network

startup_notify: true
startup_wm_class: com.fastcat.app

postinstall_scripts:
  - cp /usr/share/applications/FastCat.desktop /usr/share/applications/com.fastcat.app.desktop || true
postuninstall_scripts:
  - rm -f /usr/share/applications/com.fastcat.app.desktop
