script_template: inno_setup.iss
app_id: 9534642D-C46F-4EF0-8B3F-EF152ABEC560
app_name: fastcat
publisher: chen08209
publisher_url: https://github.com/chen08209/FlClash
display_name: fastcat
executable_name: fastcat.exe
output_base_file_name: fastcat.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: zh
    file: ..\windows\packaging\exe\ChineseSimplified.isl
  - lang: en
privileges_required: admin
